package modelo;
// Generated 18-abr-2020 20:41:47 by Hibernate Tools 4.3.1



/**
 * CaracteristicasProductos generated by hbm2java
 */
public class CaracteristicasProductos  implements java.io.Serializable {


     private CaracteristicasProductosId id;
     private Productos productos;
     private String valor;

    public CaracteristicasProductos() {
    }

    public CaracteristicasProductos(CaracteristicasProductosId id, Productos productos, String valor) {
       this.id = id;
       this.productos = productos;
       this.valor = valor;
    }
   
    public CaracteristicasProductosId getId() {
        return this.id;
    }
    
    public void setId(CaracteristicasProductosId id) {
        this.id = id;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


