package modelo;
// Generated 18-abr-2020 20:41:47 by Hibernate Tools 4.3.1



/**
 * CategoriasProductos generated by hbm2java
 */
public class CategoriasProductos  implements java.io.Serializable {


     private CategoriasProductosId id;
     private Productos productos;

    public CategoriasProductos() {
    }

    public CategoriasProductos(CategoriasProductosId id, Productos productos) {
       this.id = id;
       this.productos = productos;
    }
   
    public CategoriasProductosId getId() {
        return this.id;
    }
    
    public void setId(CategoriasProductosId id) {
        this.id = id;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }




}


