package modelo;
// Generated 18-abr-2020 20:41:47 by Hibernate Tools 4.3.1



/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable,Comparable {


     private String nombre;

    public Categorias() {
    }

    public Categorias(String nombre) {
       this.nombre = nombre;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Override
    public int compareTo(Object o) {
        Categorias c = (Categorias) o;
        
        return this.nombre.compareTo(c.nombre);
    }
}


