package modelo;
// Generated 18-abr-2020 20:41:47 by Hibernate Tools 4.3.1



/**
 * CategoriasProductosId generated by hbm2java
 */
public class CategoriasProductosId  implements java.io.Serializable{


     private String nombre;
     private int idProducto;

    public CategoriasProductosId() {
    }

    public CategoriasProductosId(String nombre, int idProducto) {
       this.nombre = nombre;
       this.idProducto = idProducto;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }


   public boolean equals(Object other) {
       CategoriasProductosId c = (CategoriasProductosId) other;
       return (this.nombre.equals(c.nombre) && this.idProducto==c.idProducto);
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         result = 37 * result + this.getIdProducto();
         return result;
   }

}


