package modelo;
// Generated 18-abr-2020 20:41:47 by Hibernate Tools 4.3.1



/**
 * CategoriasProductos generated by hbm2java
 */
public class CategoriasProductos  implements java.io.Serializable,Comparable {


     private CategoriasProductosId id;
     private Productos productos;

    public CategoriasProductos() {
    }

    public CategoriasProductos(CategoriasProductosId id, Productos productos) {
       this.id = id;
       this.productos = productos;
    }
   
    public CategoriasProductosId getId() {
        return this.id;
    }
    
    public void setId(CategoriasProductosId id) {
        this.id = id;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }

     @Override
    public boolean equals(Object o) {
        CategoriasProductos cp = (CategoriasProductos) o;
        
        return (this.id.equals(cp.id) && this.productos.equals(cp.productos));
    }
    
    @Override
    public int compareTo(Object o) {
        CategoriasProductos cp = (CategoriasProductos) o;
        
        return this.id.getNombre().compareTo(cp.getId().getNombre());
    }
    




}


