package modelo;
// Generated 18-abr-2020 20:41:47 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable,Comparable {


     private String nombre;

    public Categorias() {
    }

    public Categorias(String nombre) {
       this.nombre = nombre;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Override
    public int compareTo(Object o) {
        Categorias c = (Categorias) o;
        
        return this.nombre.compareTo(c.nombre);
    }

    @Override
    public int hashCode() {
        int hash = 5;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Categorias other = (Categorias) obj;
        if (!Objects.equals(this.nombre, other.nombre)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Categorias{" + "nombre=" + nombre + '}';
    }
}


