package modelo;
// Generated 18-abr-2020 20:41:47 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reclamaciones generated by hbm2java
 */
public class Reclamaciones  implements java.io.Serializable {


     private ReclamacionesId id;
     private Compras compras;
     private Productos productos;
     private String descripcion;
     private String estado;
     private Date fecha;

    public Reclamaciones() {
    }

    public Reclamaciones(ReclamacionesId id, Compras compras, Productos productos, String descripcion, String estado, Date fecha) {
       this.id = id;
       this.compras = compras;
       this.productos = productos;
       this.descripcion = descripcion;
       this.estado = estado;
       this.fecha = fecha;
    }
   
    public ReclamacionesId getId() {
        return this.id;
    }
    
    public void setId(ReclamacionesId id) {
        this.id = id;
    }
    public Compras getCompras() {
        return this.compras;
    }
    
    public void setCompras(Compras compras) {
        this.compras = compras;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


