package modelo;
// Generated 18-abr-2020 20:41:47 by Hibernate Tools 4.3.1



/**
 * ReclamacionesId generated by hbm2java
 */
public class ReclamacionesId  implements java.io.Serializable {


     private int idCompra;
     private int idProducto;

    public ReclamacionesId() {
    }

    public ReclamacionesId(int idCompra, int idProducto) {
       this.idCompra = idCompra;
       this.idProducto = idProducto;
    }
   
    public int getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(int idCompra) {
        this.idCompra = idCompra;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReclamacionesId) ) return false;
		 ReclamacionesId castOther = ( ReclamacionesId ) other; 
         
		 return (this.getIdCompra()==castOther.getIdCompra())
 && (this.getIdProducto()==castOther.getIdProducto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCompra();
         result = 37 * result + this.getIdProducto();
         return result;
   }   


}


