package modelo;
// Generated 18-abr-2020 20:41:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String email;
     private String nombre;
     private String password;
     private String foto;
     private String tipo;
     private Set productoses = new HashSet(0);
     private Set productoses_1 = new HashSet(0);
     private Set comprases = new HashSet(0);
     private Set valoracioneses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String email, String nombre, String password, String foto, String tipo) {
        this.email = email;
        this.nombre = nombre;
        this.password = password;
        this.foto = foto;
        this.tipo = tipo;
    }
    public Usuarios(String email, String nombre, String password, String foto, String tipo, Set productoses, Set productoses_1, Set comprases, Set valoracioneses) {
       this.email = email;
       this.nombre = nombre;
       this.password = password;
       this.foto = foto;
       this.tipo = tipo;
       this.productoses = productoses;
       this.productoses_1 = productoses_1;
       this.comprases = comprases;
       this.valoracioneses = valoracioneses;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }
    public Set getProductoses_1() {
        return this.productoses_1;
    }
    
    public void setProductoses_1(Set productoses_1) {
        this.productoses_1 = productoses_1;
    }
    public Set getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set comprases) {
        this.comprases = comprases;
    }
    public Set getValoracioneses() {
        return this.valoracioneses;
    }
    
    public void setValoracioneses(Set valoracioneses) {
        this.valoracioneses = valoracioneses;
    }

     @Override
    public boolean equals(Object o) {
        Usuarios u = (Usuarios) o;
        
        return this.getEmail().equals(u.getEmail());
    }


}


