package modelo;
// Generated 18-abr-2020 20:41:47 by Hibernate Tools 4.3.1



/**
 * ValoracionesId generated by hbm2java
 */
public class ValoracionesId  implements java.io.Serializable {


     private String emailCliente;
     private int idProducto;

    public ValoracionesId() {
    }

    public ValoracionesId(String emailCliente, int idProducto) {
       this.emailCliente = emailCliente;
       this.idProducto = idProducto;
    }
   
    public String getEmailCliente() {
        return this.emailCliente;
    }
    
    public void setEmailCliente(String emailCliente) {
        this.emailCliente = emailCliente;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ValoracionesId) ) return false;
		 ValoracionesId castOther = ( ValoracionesId ) other; 
         
		 return ( (this.getEmailCliente()==castOther.getEmailCliente()) || ( this.getEmailCliente()!=null && castOther.getEmailCliente()!=null && this.getEmailCliente().equals(castOther.getEmailCliente()) ) )
 && (this.getIdProducto()==castOther.getIdProducto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmailCliente() == null ? 0 : this.getEmailCliente().hashCode() );
         result = 37 * result + this.getIdProducto();
         return result;
   }   


}


