package modelo;
// Generated 18-abr-2020 20:41:47 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Valoraciones generated by hbm2java
 */
public class Valoraciones  implements java.io.Serializable {


     private ValoracionesId id;
     private Productos productos;
     private Usuarios usuarios;
     private int puntuacion;
     private String descripcion;
     private Date fecha;

    public Valoraciones() {
    }

    public Valoraciones(ValoracionesId id, Productos productos, Usuarios usuarios, int puntuacion, String descripcion, Date fecha) {
       this.id = id;
       this.productos = productos;
       this.usuarios = usuarios;
       this.puntuacion = puntuacion;
       this.descripcion = descripcion;
       this.fecha = fecha;
    }
   
    public ValoracionesId getId() {
        return this.id;
    }
    
    public void setId(ValoracionesId id) {
        this.id = id;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public int getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(int puntuacion) {
        this.puntuacion = puntuacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


